### ISSUE TITLE
Dirección de envíos

### ISSUE THREAD

**Issue by Nidev-lab** [juedsay/ProyectoFinal_RC#21]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con usuario.
3. Hice unos pedidos.

## Resultado esperado

• Al pedir la "dirección de envió" encontrar un limite de caracteres.

## Resultado actual

• No hay un limite de caracteres a poner.

## Captura

![image](https://github.com/juedsay/ProyectoFinal_RC/assets/53904695/06000f28-3661-4cf7-89e5-4d355a7c46f5)
Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juancinfante** [comment]
En un principio el input tenia un max length de 200 caracteres, quizá a simple vista no se apreciaba. De todas formas lo solucione y lo cambie a 50 caracteres así se aprecia mejor el corte.
