### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by Nidev-lab** [juedsay/ProyectoFinal_RC#22]
## Proceso

1. Ingrese a la pagina.
2. Quise registrar un nuevo usuario.

## Resultado esperado

• Que en el formulario de registro solo se puedan usar letras para poner el nombre del usuario.

## Resultado actual

•  Se puede poner cualquier tipo de carácter en dicho lugar.

## Captura

![image](https://github.com/juedsay/ProyectoFinal_RC/assets/53904695/cd71128d-dc45-4e35-bdc5-ec90d75b6766)
![image](https://github.com/juedsay/ProyectoFinal_RC/assets/53904695/22d196e7-3c81-471b-8959-f020789f390a)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juancinfante** [comment]
Solucionado.
